name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  static-analysis:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 20.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout to ${{ github.ref }}
        uses: actions/checkout@v4
      - name: Setup turbo cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ matrix.node-version }}-turbo-
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.6.2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Lint types
        run: pnpm lint:types
        if: always()
      - name: Lint semantic
        run: pnpm lint:semantic
        if: always()
      - name: Lint format
        run: pnpm lint:format
        if: always()
      - name: Lint commits
        run: pnpm lint:commits
        if: always()

  runtime-compat:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 18.x
          - 20.x
        include:
          - os: windows-latest
            node-version: 20.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout to ${{ github.ref }}
        uses: actions/checkout@v4
      - name: Setup turbo cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ matrix.node-version }}-turbo-
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^8.6.2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Build
        run: pnpm build
      - name: Unit test
        run: pnpm test:unit
        if: always()
